spring.application.name=security-scanner
server.servlet.session.timeout=1h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false